#!/usr/bin/env bash
# Displays the time for 12 hours and 50 minutes
i=1
while [ "$i" -le 12 ]
do
echo "Hour: $i"
minute=1
while [ $minute -le 59 ]
do
echo "$minute"
(( minute++ ))
done
(( i++ ))
done
